### PR TITLE
[BUGFIX] Remove manual autoloading of autoloadable classes

### PR DESCRIPTION
**Pull request by oliverklee**
This fixes PHPStan errors in extensions that use rn_base.

In addition, this also should slightly improve performance as classes
now are loaded on demand more often.

### CODE REVIEW

**Comment by digedag** [comment]
You are very welcome to provide those fixes against branch `refactor_domain`,  but not against `master`. I'm currently move all classes to PSR-4 namespaces. This change against `master` will cause unnecessary merge conflicts.

**Comment by oliverklee** [comment]
@digedag I think the `refactor_domain` branch already removed most (if not all) these occurrences.

So maybe we can solve this problem differently: Currently rn_base breaks PHPStan and Rector for my classes that use mkforms, and I'd really appreciate a quick solution so I can harness the power of those two tools when refactoring my extensions. Would it be possible to have a release timely release of rn_base with the fixes from the `refactor_domain` branch included (e.g., a version 1.14.0 or 2.0.0)?

How can we solve this for me so I can use PHPStan and Rector?

**Comment by digedag** [comment]
I want to release 1.14 next week. :-)

**Comment by digedag** [comment]
I close this PR as it should be obsolete.

**Pull request closed without merging**
