### PR TITLE
[CLEANUP] Fix undefined variables

### PR DESCRIPTION
**Pull request by oliverklee**

### CODE REVIEW

**Comment by oliverklee** [comment]
@digedag gentle ping :-)

**Comment by oliverklee** [comment]
@digedag Rebased and repushed.

**Comment by digedag** [comment]
@oliverklee this MR will cause too many conflicts in branch `refactor_domain`. So it will be merged later.

**Comment by digedag** [comment]
Feel free to fix this PR. Will be merged if possible.

**Comment by oliverklee** [comment]
This is now obsolete. Closing.

**Pull request closed without merging**
